AllCops:
  TargetRubyVersion: 2.7

  Exclude:
    - 'exp/**/*'

# Style/RegexpLiteral:
#   EnforcedStyle: percent_r

Metrics/LineLength:
  Max: 120

Style/AsciiComments:
    Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Rails/TimeZone:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
